export const GET_PROCLAMATIONS = "GET_ENACT_PROCLAMATIONS"
export const GET_PROCLAMATIONS_SUCCESS = "GET_ENACT_PROCLAMATIONS_SUCCESS"
export const GET_PROCLAMATIONS_FAIL = "GET_ENACT_PROCLAMATIONS_FAIL"

export const DISCARD_PROCLAMATION = "DISCARD_ENACT_PROCLAMATION"
export const DISCARD_PROCLAMATION_SUCCESS = "DISCARD_ENACT_PROCLAMATION_SUCCESS"
export const DISCARD_PROCLAMATION_FAIL = "DISCARD_ENACT_PROCLAMATION_FAIL"