export const ENACT_PROCLAMATION = "ENACT_PROCLAMATION"
export const ENACT_PROCLAMATION_SUCCESS = "ENACT_PROCLAMATION_SUCCESS"
export const ENACT_PROCLAMATION_FAIL = "ENACT_PROCLAMATION_FAIL"

export const GET_PROCLAMATIONS = "GET_ENACT_PROCLAMATIONS"
export const GET_PROCLAMATIONS_SUCCESS = "GET_ENACT_PROCLAMATIONS_SUCCESS"
export const GET_PROCLAMATIONS_FAIL = "GET_ENACT_PROCLAMATIONS_FAIL"