export const JOIN_GAME = "JOIN_GAME"
export const JOIN_GAME_SUCCESS = "JOIN_GAME_SUCCESS"
export const JOIN_GAME_FAIL = "JOIN_GAME_FAIL"

export const START_GAME = "START_GAME"
export const START_GAME_SUCCESS = "START_GAME_SUCCESS"
export const START_GAME_FAIL = "START_GAME_FAIL"
